version: '3.8'

services:
  web:
    image: ghcr.io/${{ github.repository }}:latest # <--- ¡CAMBIO AQUÍ!
    container_name: pablomc20_web
    ports:
      - "8081:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: always
