name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code on runner # Necesario para copiar el docker-compose.yml
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry # Necesario para que el VPS pueda hacer docker pull
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # Paso: Copiar el docker-compose.yml actualizado al VPS
      # Asegura que el VPS siempre tenga la versión que referencia la imagen
      - name: Copy docker-compose.yml to VPS
        run: |
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/developer/apps/frontend/pablomc20/docker-compose.yml

      - name: Deploy via SSH with Docker Compose
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          # Navega al directorio de tu proyecto donde está docker-compose.yml
          cd /home/developer/apps/frontend/pablomc20

          # Detiene y elimina los servicios existentes definidos en docker-compose.yml.
          # Esto liberará el puerto 8081 antes de que se intente levantar el nuevo.
          echo "Stopping and removing existing Docker Compose services..."
          docker compose down || true 

          # Limpia cualquier recurso Docker no utilizado.
          echo "Pruning old Docker images and containers..."
          docker system prune -f

          # Descarga la imagen más reciente desde GitHub Container Registry.
          echo "Pulling the latest image from GHCR.IO..."
          docker pull ghcr.io/${{ github.repository }}:latest

          # Levanta los servicios. Docker Compose detectará la nueva imagen y reemplazará el contenedor antiguo.
          # Ya NO usamos --build aquí porque la imagen ya está pre-construida.
          echo "Starting Docker Compose services..."
          docker compose up -d --remove-orphans 
          
          echo "Deployment complete!"
          EOF